version: "3.8"

services:
  nginx:
    image: nginx
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - '80:80'
    depends_on:
      - nextjs
      - fastify
  nextjs:
    build: ./nextjs
    ports:
      - '8040:8040'
  fastify:
    build: ./fastify
    ports:
      - '8080:8080'